version: "3.7"

services:
  chrome-app:
    image: chrome-app-test
    build: ./chrome-react-app
    volumes:
      - type: bind
        source: ./chrome-react-app
        target: /usr/local/src
    depends_on: 
      - backend-go

  redis:
      volumes:
        - redis_data:/data

volumes: 
    redis_data: